name: tutorial2
on: workflow_dispatch

jobs:
    job1:
        name: job1
        runs-on: ubuntu-latest
        steps:
        - name: setup
          run: |
            echo "Current date:"
            date
          
            echo "Working directory:"
            pwd
          
            echo "Directory contents:"
            ls -la


